device_management/device_management/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('login.urls')),

]

device_management/login/urls.py
from django.conf.urls import url
from django.contrib import admin
from login import views

 

urlpatterns = [
    url(r'^index/', views.index),
    url(r'^login/', views.login),
    url(r'^register/', views.register),
    url(r'^logout/', views.logout),
    url(r'^webye/', views.webye),
    url(r'^contact', views.contact),
    url(r'^', views.index),
]

device_management/login/models.py
# Create your models here.

from django.db import models
 
 
class User(models.Model):
    '''用户表'''
 
    gender = (
        ('male','男'),
        ('female','女'),
    )
 
    name = models.CharField(max_length=128,unique=True)
    password = models.CharField(max_length=256)
    email = models.EmailField(unique=False)
    sex = models.CharField(max_length=32,choices=gender,default='男')
    c_time = models.DateTimeField(auto_now_add=True)
 
    def __str__(self):
        return self.name
 
    class Meta:
        ordering = ['c_time']
        verbose_name = '用户'
        verbose_name_plural = '用户'



class Phone(models.Model):
    '''手机表'''
    _id = models.AutoField(primary_key=True,)

    device_name = models.CharField(max_length=128)
    pinpai = models.CharField(max_length=128)
    ram = models.CharField(max_length=128)
    cpu = models.CharField(max_length=128)
    system_version = models.CharField(max_length=128)
    holder_people  = models.CharField(max_length=128)
 
    def __str__(self):
        return self.device_name
 
    class Meta:
        ordering = ['-pinpai']   #加负号表示倒序
        verbose_name = '手机'
        verbose_name_plural = '手机'

device_management/login/views.py
from django.http import HttpResponse
# Create your views here.

# login/views.py
 
from django.shortcuts import render,redirect
from .models import User
from .models import Phone

def index(request):
    phone = Phone.objects.all()
    return render(request,'index.html', {'phone': phone,})

def login(request):

	if request.session.get('is_login',None):
		return redirect('/index')
	if request.method == "POST":

		username = request.POST.get('username', None)
		password = request.POST.get('password', None)
		print(username)
		print(password)
		message = "所有字段都必须填写！"
		if username and password:  # 确保用户名和密码都不为空
		    username = username.strip()
		    # 用户名字符合法性验证
		    # 密码长度验证
		    # 更多的其它验证.....
		    try:
		    	user = User.objects.get(name=username)
		    	if user.password == password:
		    		message = "登录成功"
		    		request.session['is_login'] = True
		    		request.session['user_id'] = user.id
		    		print(request.session['user_id'])
		    		request.session['user_name'] = user.name
		    		print(request.session['user_name'])
		    		return redirect('/login/index/')
		    	else:
		        	message = "密码不正确！"
		    except:
		        message = "用户名不存在！"
		return render(request, 'login.html', {"message": message})
	return render(request, 'login.html')
 

def register(request):

    if request.method == "POST":  # 获取数据
        username = request.POST.get('username')

        password1 = request.POST.get('password1')
        password2 = request.POST.get('password2')
        email = request.POST.get('email')
        print(email)
        sex = request.POST.get('sex')
        print(sex)
        if password1 != password2:  # 判断两次密码是否相同
            message = "两次输入的密码不同！"
            return render(request, 'register.html', locals())
        else:
            same_name_user = User.objects.filter(name=username)
            if same_name_user:  # 用户名唯一
                message = '用户已经存在，请重新选择用户名！'
                return render(request, 'register.html', locals())
            same_email_user = User.objects.filter(email=email)
            if same_email_user:  # 邮箱地址唯一
                message = '该邮箱地址已被注册，请使用别的邮箱！'
                return render(request, 'register.html', locals())

            # 当一切都OK的情况下，创建新用户
            User.objects.create(name=username,password=password1,email=email,sex=sex)
            message = "恭喜您，注册成功！"

            return render(request, 'register.html', locals())
            #return redirect('/login/register/', locals())  # 自动跳转到登录页面

    return render(request, 'register.html', locals())
 
#def logout(request):
#    pass
#    request.session['is_login'] = False
#    return redirect('/login/index')

def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/login/index/")
    request.session.flush()    #清除session的所有信息
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/login/index/")

def webye(request):  #flatlab例子，所有js，所有css，所有img听我号令

    phone = Phone.objects.all()
    for item in phone:
        print(item)
        print(item._id)
        print(item.device_name)
        print(item.pinpai)
        print(item.ram)
        print(item.cpu)
        print(item.system_version)
        print(item.holder_people)
    return render(request, 'index_table_for_flatlab.html', {'phone': phone,})


def contact(request):
    return HttpResponse("Hello, world. You're at the contact index.")


'''
def login(request):
    return HttpResponse("Hello, world. You're at the login index.")


def logout(request):
    return HttpResponse("Hello, world. You're at the logout index.")


def register(request):
    return HttpResponse("Hello, world. You're at the register index.")

def webye(request):
    return HttpResponse("Hello, world. You're at the webye index.")
'''

device_management/login/templates/a.html
aaaaaaaaaaaaaaaa

device_management/login/templates/b.html
bbbbbbbbbbbbbbbbbb

device_management/login/templates/base.html
{% load staticfiles %}
 
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>
 
    <!-- Bootstrap -->
    <link href="{% static '/css/bootstrap.min.css' %}" rel="stylesheet">
 
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
        <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="/static/img/favicon.png">


    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="/static/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />
    <link rel="stylesheet" href="/static/assets/data-tables/DT_bootstrap.css" />

      <!--right slidebar-->
      <link href="/static/css/slidebars.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
    
    {% block css %}{% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
            <span class="sr-only">切换导航条</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">设备管理系统</a>
        </div>
 
        <!-- Collect the nav links, forms, and other content for toggling -->

 <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav">
            <li ><a href="/">主页</a></li>
            <li ><a href="/index/">index</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              {% if request.session.is_login %}
                  <li><a href="#">当前在线：{{ request.session.user_name }}</a></li>
                  <li><a href="/logout/">登出</a></li>
              {% else %}
                  <li><a href="/login/">登录</a></li>
                  <li><a href="/register/">注册</a></li>
              {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->

      </div><!-- /.container-fluid -->
 
    {% block content %}{% endblock %}
 
 
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'js/jquery-3.2.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static '/js/bootstrap.min.js' %}"></script>
  </body>
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/static/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/static/js/jquery.scrollTo.min.js"></script>
    <script src="/static/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script type="text/javascript" src="/static/assets/data-tables/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/static/assets/data-tables/DT_bootstrap.js"></script>
    <script src="/static/js/respond.min.js" ></script>

  <!--right slidebar-->
  <script src="/static/js/slidebars.min.js"></script>

    <!--common script for all pages-->
    <script src="/static/js/common-scripts.js"></script>

      <!--script for this page only-->
      <script src="/static/js/editable-table.js"></script>

</html>

device_management/login/templates/index.html
{% extends 'base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
    {% if request.session.is_login %}
    <!--<h1>你好,{{ request.session.user_name }}！欢迎回来！</h1>-->


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="/static/img/favicon.png">

    <title>Dynamic Table</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="/static/assets/font-awesome/css/font-awesome.css" rel="stylesheet" />

    <!--dynamic table-->
    <link href="/static/assets/advanced-datatable/media/css/demo_page.css" rel="stylesheet" />
    <link href="/static/assets/advanced-datatable/media/css/demo_table.css" rel="stylesheet" />
    <link rel="stylesheet" href="/static/assets/data-tables/DT_bootstrap.css" />
      <!--right slidebar-->
      <link href="/static/css/slidebars.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/style-responsive.css" rel="stylesheet" />

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

  <section id="container" class="center">



    <!--sidebar start-->
      <aside>
          <div id="sidebar"  >
              <!-- sidebar menu start-->
              <ul class="sidebar-menu" id="nav-accordion">
                  <li>
                      <a href="/logout/">
                          <i class="fa fa-dashboard"></i>
                          <span>返回主页</span>
                      </a>
                  </li>

                  <li class="sub-menu">
                      <a href="index_table_for_flatlab.html">
                          <i class="fa fa-laptop"></i>
                          <span>设备列表</span>
                      </a>
    
                  </li>

                  <li class="sub-menu">
                      <a href="/contact/">
                          <i class="fa fa-book"></i>
                          <span>联系方式</span>
                      </a>
 
                  </li>

                  <li class="sub-menu">
                      <a href="/webye/">
                          <i class="fa fa-cogs"></i>
                          <span>Components</span>
                      </a>

                  </li>


              </ul>
              <!-- sidebar menu end-->
          </div>
      </aside>
      <!--sidebar end-->
      <!--main content start-->
      <section id="main-content" class="center">  <!-- main-conten 决定了有没有侧边栏的排位空间-->
          <section class="wrapper">
              <!-- page start-->
              <div class="row center">
                <div class="col-sm-12">
              <section class="panel">
              <header class="panel-heading">
                  设备表
             <span class="tools pull-right">
                <a href="javascript:;" class="fa fa-chevron-down"></a>
                <a href="javascript:;" class="fa fa-times"></a>
             </span>
              </header>
              <div class="panel-body">
              <div class="adv-table">
              <table  class="display table table-bordered table-striped" id="dynamic-table">
              <thead>
              <tr>
                  <th>品牌 - 型号</th>
                  <th>RAM容量</th>
                  <th>CPU型号</th>
                  <th class="hidden-phone">系统版本</th>
                  <th class="hidden-phone">持有人/现用人</th>
              </tr>
              </thead>
              <tbody>


              {% for item in phone %}
              <tr class="gradeX">
                  <td>
                    {{item.device_name}} -  {{item.pinpai}}
                  </td>
                  <td>{{item.ram}}</td>
                  <td>{{item.cpu}}</td>
                  <td class="center hidden-phone">{{item.system_version}}</td>
                  <td class="center hidden-phone">{{item.holder_people}}</td>
              </tr>
              {% endfor %}

              </tbody>
              <tfoot>
              <tr>
                  <th>品牌 - 型号</th>
                  <th>RAM容量</th>
                  <th>CPU型号</th>
                  <th class="hidden-phone">系统版本</th>
                  <th class="hidden-phone">持有人/现用人</th>
              </tr>
              </tfoot>
              </table>

              </div>
              </div>

              </section>
              </div>
              </div>

<a href= "/admin/login/phone/" class="btn btn-shadow btn-info" type="submit" value="修改"/>修改</a> 

          </section>
      </section>
      <!--main content end-->
 

  </section>

    <!-- js placed at the end of the document so the pages load faster -->

    <script src="/static/js/jquery.js"></script>
    <script src="/static/js/jquery-ui-1.9.2.custom.min.js"></script>
    <script src="/static/js/jquery-migrate-1.2.1.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script class="include" type="text/javascript" src="/static/js/jquery.dcjqaccordion.2.7.js"></script>
    <script src="/static/js/jquery.scrollTo.min.js"></script>
    <script src="/static/js/jquery.nicescroll.js" type="text/javascript"></script>
    <script type="text/javascript" language="javascript" src="/static/assets/advanced-datatable/media/js/jquery.dataTables.js"></script>
    <script type="text/javascript" src="/static/assets/data-tables/DT_bootstrap.js"></script>
    <script src="/static/js/respond.min.js" ></script>

    <!--right slidebar-->
    <script src="/static/js/slidebars.min.js"></script>

    <!--dynamic table initialization -->
    <script src="/static/js/dynamic_table_init.js"></script>


    <!--common script for all pages-->
    <script src="/static/js/common-scripts.js"></script>

  </body>
</html>













    {% else %}
    <h1>你尚未登录，只能访问公开内容！</h1>
    {% endif %}

    
{% endblock %}

device_management/login/templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}登录{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
 
 
{% block content %}
    <nav></nav>
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="/login/" method="post">
 
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
 
                {% csrf_token %}
                <h2 class="text-center">欢迎登录</h2>
                <div class="form-group">
                    <label for="id_username">用户名：</label>
                    <input type="text" name='username' class="form-control" id="id_username" placeholder="Username"
                           autofocus required>
                </div>
                <div class="form-group">
                    <label for="id_password">密码：</label>
                    <input type="password" name='password' class="form-control" id="id_password" placeholder="Password"
                           required>
                </div>
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

device_management/login/templates/register.html
{#login/templates/register.html#}
 
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}注册{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}
 
 
{% block content %}
<nav></nav>
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="/register/" method="POST">
 
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
 
                {% csrf_token %}
                <h2 class="text-center">欢迎注册</h2>
                <div class="form-group">
                    <label for="id_username">用户名：</label>
                    <input type="text" name='username' class="form-control" id="id_username" placeholder="Username"
                           autofocus required>
                </div>
                <div class="form-group">
                    <label for="id_password">密码：</label>
                    <input type="password" name='password1' class="form-control" id="id_password" placeholder="Password"
                           required>
                </div>
                                <div class="form-group">
                    <label for="id_password">确认密码：</label>
                    <input type="password" name='password2' class="form-control" id="id_password" placeholder="Password"
                           required>
                </div>
                                <div class="form-group">
                    <label for="id_email">邮箱：</label>
                    <input type="text" name='email' class="form-control" id="id_email" placeholder="邮箱"
                           required>
                </div>
                                <div class="form-group">
                    <p><label for="id_sex">性别：</label></p>


                <select name="sex" id="id_sex" class="btn">
                <option value="male">男</option>
                <option value="female">女</option>
          		</select>

                </div>

                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}